### ISSUE TITLE
Ruby version related issue?

### ISSUE THREAD

**Issue by skypanther** [jonmagic/csv2md#1]
I tried installing & using csv2md today but I'm getting the following error. Perhaps a ruby version problem?

```shell
≫ cat android.md | csv2md -r
/Users/timpoulsen/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require': /Users/timpoulsen/.rvm/gems/ruby-1.9.3-p385/gems/csv2md-1.1.0/lib/csv2md.rb:6: syntax error, unexpected tLABEL, expecting ')' (SyntaxError)
  def initialize(input: nil)
                       ^
/Users/timpoulsen/.rvm/gems/ruby-1.9.3-p385/gems/csv2md-1.1.0/lib/csv2md.rb:65: syntax error, unexpected keyword_end, expecting $end
	from /Users/timpoulsen/.rvm/rubies/ruby-1.9.3-p385/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /Users/timpoulsen/.rvm/gems/ruby-1.9.3-p385/gems/csv2md-1.1.0/bin/csv2md:3:in `<top (required)>'
	from /Users/timpoulsen/.rvm/gems/ruby-1.9.3-p385/bin/csv2md:19:in `load'
	from /Users/timpoulsen/.rvm/gems/ruby-1.9.3-p385/bin/csv2md:19:in `<main>'
	from /Users/timpoulsen/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `eval'
	from /Users/timpoulsen/.rvm/gems/ruby-1.9.3-p385/bin/ruby_noexec_wrapper:14:in `<main>'
```

In case:
```shell
≫ ruby --version
ruby 1.9.3p385 (2013-02-06 revision 39114) [x86_64-darwin11.4.2]
```

OS X Yosemite 10.10.3

**Comment by jonmagic** [comment]
Doh, so sorry I missed this, I wasn't subscribed to my own repo :/ I should totally update this to not use [kwargs](https://robots.thoughtbot.com/ruby-2-keyword-arguments).

**Comment by jonmagic** [comment]
Just released a new version that works with ruby versions < 2.0.0 https://rubygems.org/gems/csv2md/versions/1.1.1

**Comment by skypanther** [comment]
Thanks! I'll give it another try.
